language: go

os: linux

arch:
   - amd64
  - ppc64le

sudo: required
#tem que fazer um fork e tirar esse git clone daqui
services:
  - docker
go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x" 
  - "1.13.4"
  
install:
  - GO111MODULE=off go get golang.org/x/lint/golint
script:
  - make

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential python3 tar wget

script:
  - git clone https://github.com/poseidon/matchbox.git
  - cd matchbox
  - make
  - ./bin/matchbox -version